### ISSUE TITLE
Remove nameHash, bodyHash, spaceHash

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#10]
### Expected behavior

We don't need to add the newly added fields in the `erc712` branch for:

- `nameHash`
- `bodyHash`
- `spaceHash`

---

Here is a record from a Slack conversation:

> _Jeremiah Trein_
For ERC712 Snapshot Hub, are the new POST /message requirements for spaceHash, nameHash, bodyHash hashed using a function like Web3.utils.sha3

> _Felipe Forbeck_
Yes, they use sha3. But I am changing these attribute names to: space, name and body as requested per **David Roon**

### Actual behavior

They are required by the API, but we only use them before submitting to Moloch.

### Steps to reproduce the behavior

N/A

---

cc: @adridadou

**Comment by jtrein** [comment]
Important note from @fforbeck :

> about removing the nameHash, spaceHash, bodyHash I am not sure, because they are part of the signature of ERC712, if we remove them it changes the signature and then it also breaks the signature validation

I think we will need to use the [`prepareMessage`](https://github.com/openlawteam/laoland/blob/master/utils/offchain_voting.js#L221) helper to provide Snapshot this information.

**Comment by jtrein** [comment]
OK, confirmed with @adridadou that we can remove these values from the API. Below is an excerpt of the conversation:

> regarding nameHash an bodyHash, it does not change the signature scheme because using name string or nameHash bytes32 is basically the same

> we only need it when we call the smart contract

> because the name of the property does not affect the result of the hash only the values (and a certain order )

**Comment by jtrein** [comment]
https://github.com/openlawteam/snapshot-hub/blob/erc-712/server/index.ts#L212

This one does not mention `nameHash` or `bodyHash` but I think the length requirement needs updating.

**Comment by fforbeck** [comment]
> https://github.com/openlawteam/snapshot-hub/blob/erc-712/server/index.ts#L212
> 
> This code does not mention `nameHash` or `bodyHash` but I think the length requirement needs updating.

actually we have that as the last 2 parameters, it is just the line comment that is wrong. I already updated that. Thanks for flagging.

**Comment by fforbeck** [comment]
Done: `docker pull openlaw/snapshot-hub:erc-712-7dc333f5`
