### ISSUE TITLE
[docs] List what environment variables are needed to run the app locally

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#12]
### Expected behavior

It would be nice to list the essential variables we need to place in our `env.local`. Also a link to Pinata service would be helpful 😎 (pinning service API keys).

### Actual behavior

Currently it's a bit of a guessing game to get the app to run with the correct environment variables. 

### Steps to reproduce the behavior

n/a

**Comment by fforbeck** [comment]
Docs added. Closing
