### ISSUE TITLE
Get a Proposal by its uniqueIdDraft

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#13]
### Expected behavior

We sometimes start with a Snapshot _Draft_ type as we do not want to immediately "sponsor" it. This means we need to always use the Draft's ID (the original id) to reference the proposal going forward where we have stored it in immutable systems like Moloch DAO v3.

In the case of Snapshot _Proposal_ type we need to be able to query the `GET .../proposal/...` API by the `uniqueIdDraft` field. This means, after we have created a Snapshot Proposal we can still get the correct information using the original ID.

### Actual behavior

Today, we need to `GET` all proposals and `filter()` them on the client.

### Steps to reproduce the behavior

n/a

**Comment by fforbeck** [comment]
@jtrein 
Get proposal by id endpoint was updated to filter proposals by their draft ids if the filter flag is present in the query parameters.


#### Get Proposal by Draft Id

Request

```
GET {{baseUrl}}/api/:space/proposal/:id?isUniqueDraftId=true HTTP/1.1
```

Response

```json
{
  "0x1433749efa5a3c2ef89aa0962159fb88cbd834681386e230d07f4a443c931682": {
    "address": "0xEd7B3f2902f2E1B17B027bD0c125B674d293bDA0",
    "msg": {
      "version": "0.2.0",
      "timestamp": "1611091325",
      "token": "0x8f56682a50becb1df2fb8136954f2062871bc7fc",
      "type": "proposal",
      "payload": {
        "body": "ASd",
        "choices": ["Yes", "No"],
        "end": 1611094925,
        "metadata": {
          "uuid": "0xEd7B3f2902f2E1B17B027bD0c125B674d293bDA0",
          "private": 0,
          "type": "governance",
          "subType": "governance"
        },
        "name": "ASd",
        "start": 1611091325,
        "snapshot": 1
      }
    },
    "sig": "0xf2469a902f630f4d29e439baf9f94dd405901c8e6e0d702c8b47676ea7e35f271c858babcc168a8dd0e1689d1e66f7dfc1a876c4b62c7f1c9042afbd2dffff491c",
    "authorIpfsHash": "0x1433749efa5a3c2ef89aa0962159fb88cbd834681386e230d07f4a443c931682",
    "relayerIpfsHash": "QmU5Zd4zYP812RCKNM8esELNPuqASGfDxRiQDFQRCvGbvY",
    "actionId": "0x4539Bac77398aF6d582842F174464b29cf3887ce"
  }
}
```

Closing.
