### ISSUE TITLE
Add votes data to proposal(s)

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#14]
### Expected behavior

Adding a `votes` field to the response payload data for `/proposal` and `/proposals`.

Perhaps making this opt-in would be wise, i.e. Using a query param like `?includeVotes=true` for each Proposal endpoint.

**Example Response inside `msg` root**

```js
{
  "0xfaa09abe714291de6d3b5a6daa0330e5d4367188680b02cbc042243269fa050c": {
    ...,
    "msg": {
      ...
      "votes": ...
    },
    ...
  }
}
```

### Actual behavior

Must make separate network calls to get votes for each proposal.

**Comment by fforbeck** [comment]
Done:
- https://github.com/openlawteam/snapshot-hub/tree/erc-712#get-all-proposals-including-votes
- https://github.com/openlawteam/snapshot-hub/tree/erc-712#get-proposal-including-votes
