### ISSUE TITLE
Add votes data to proposals by action ID

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#15]
### Expected behavior

Building off of #14 we should be able to add `votes: ...` to the proposals by action ID. This late addition was an oversight on my part 😁.

### Actual behavior

Today, we must 1) Fetch all proposals and votes 2) Filter all proposals

### Steps to reproduce the behavior

n/a

**Comment by fforbeck** [comment]
implemented by @jtrein 
Closing.
