### ISSUE TITLE
Add "data" key to proposals, proposals by action ID results

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#17]
### Expected behavior

Similar to fetching a single Proposal's data, we should be able to get the `data: { ... }` information for all Proposals. This information is needed as the Draft hash should be accessible on every Proposal struct returned.

i.e. If we need the Draft hash to reference the blockchain.

### Actual behavior

The `data` key is not provided in results for all Proposals, or Proposals by action ID.

### Steps to reproduce the behavior

n/a

**Comment by fforbeck** [comment]
Implemented by @jtrein 
Closing.
