### ISSUE TITLE
Create spaces

### ISSUE THREAD

**Issue by fforbeck** [openlawteam/snapshot-hub#27]
- molochv3

**Comment by jtrein** [comment]
This is my best guess for Rinkeby:

```
space: "molochv3"
// the current Rinkeby address on https://molochv3.org
token: "0x252e780E5ef2Ba689034BfD7453438A33c73FCfF"
```

**Comment by jdville03** [comment]
FYI - the current Rinkeby address on https://molochv3.org is now `0xf1912ea06051024E610587d9bf926a252dD7560B`. But not sure how we want to handle the token because I'm sure we don't want to have to keep updating it just for development purposes.

**Comment by jdville03** [comment]
`tribute` and `museo` spaces were created.
