### ISSUE TITLE
Update CORS allowed domains env var

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#36]
### Expected behavior

- New domain for the Tribute development should be added to CORS `ALLOWED_DOMAINS`: http://tributedao.com, https://tributedao.com
- https://molochv3.org should be removed from CORS `ALLOWED_DOMAINS`

### Actual behavior

- http://tributedao.com produces a CORS error

### Steps to reproduce the behavior

- Visit http://tributedao.com and an error message will read: `"Snapshot API is not responding."`

**Comment by jdville03** [comment]
@jtrein do you mind checking again? I already updated the allowed domains yesterday and the site seems to be working fine for me. I don't get that error.

**Comment by jtrein** [comment]
Thank you. It's working, we're just waiting on https://github.com/openlawteam/tribute-ui/issues/307.
