### ISSUE TITLE
Regression: Hot reloading not working in development

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#46]
### Expected behavior

When saving a file in `snapshot-hub` the vue express server should reload. I think this may be a regression from https://github.com/openlawteam/snapshot-hub/commit/5b7bcf7d41beb2ae359e38b81975f7fc042a97ac.

### Actual behavior

When saving a file it now does not reload. You must close the docker session and restart manually.

### Steps to reproduce the behavior

Start the local development server then try saving a file.

**Comment by fforbeck** [comment]
my bad @jtrein ! Just reverted that commit. Thanks for flagging.

**Comment by jtrein** [comment]
Thank you!
