### ISSUE TITLE
Local spaces JSON for Docker builds

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#7]
### Expected behavior

It would be nice to be able to augment the `spaces/` with a local config file of local spaces which then gets loaded for local Docker development.

### Actual behavior

Currently, the only environments which gets loaded are `prod` and `dev`.

### Steps to reproduce the behavior

N/A

**Comment by jtrein** [comment]
It would be nice if it is loaded, but `.gitignore`d so we don't need to commit it.

I am also not sure if this will mess up the environment paradigm too much. In other words: will adding a new `local` environment complicate things?

**Comment by fforbeck** [comment]
not at all @jtrein 
we can add that and set an env var to indicate the env ENV (prod,dev,local), so the app to loads the spaces file based on that as you suggested. 
I can take a look on that once I get the `Draft` type and message verification working properly.

**Comment by fforbeck** [comment]
@jtrein I've added the new environment called `local`, the json is equal to the `dev`. Closing.
