### ISSUE TITLE
Add a unique hash to the Draft, Proposal, Vote data

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#9]
### Expected behavior

Today we have no unique ID in Snapshot Hub for proposals and their votes. We need the option to create a unique ID because it will help us easily couple a Snapshot proposal to a Moloch proposal (`bytes32 proposalId`).

I believe there is a helper function in the `laoland` JS libs which will give us a unique hash for the ID. We will then pass this unique ID to Snapshot for types `draft`, `proposal` and `vote`*. In the case of "sponsoring" Drafts (i.e. creating a `proposal`), we will use this [unique hash to invalidate it](https://github.com/openlawteam/snapshot-hub/issues/8). We will also use it to submit the proposal to Moloch for use as the Moloch proposal's ID.

_* I think it might be good to include it for votes, but I am not sure - open question_

```js
// Example submission data

{
  // ...
  "uniqueId": string
  // ...
}
```

### Actual behavior

There is no unique ID. Only an IPFS content hash.

### Steps to reproduce the behavior

N/A

---

cc: @adridadou

**Comment by fforbeck** [comment]
done
